version: '3.8'
services:
  jenkins:
    restart: always
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - "127.0.0.1:8080:8080"
#     - "8080:8080"
     - "127.0.0.1:50000:50000"
#     - "50000:50000"
    volumes:
      - /opt/keys:/opt/keys
      - /opt/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

